### ISSUE TITLE
Remove parsers on ant clean

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#199] opened 2019-05-04 10:16 UTC
I just updated VerCors using `ant clean` and `ant`, and the error I got was something along the lines of:

```
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.2ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.2ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.2ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.2FAILURE: class has no static field CH_COMMENT
```

Can we clean up the parser directory on doing `ant clean`? Or is `ant clean && ant` not the preferred way to reinstall a newer version?

**Comment by niomaster** [comment] 2019-05-06 09:43
I bumped the ANTLR version recently, but I cannot reproduce this. Maybe you have the wrong ANTLR version manually on your classpath? That shouldn't be the case though, as it used to be added to the classpath by the `build.xml` in `parsers` regardless.

**Comment by sjcjoosten** [comment] 2019-05-06 09:55
Removing all files in parser fixed the issue for me, so I don't think it's a manual classpath issue.

**Comment by sjcjoosten** [comment] 2019-05-06 10:47
Cannot reproduce

**Comment by niomaster** [comment] 2019-05-09 07:21
For anyone finding this issue later: it seems that SBT sometimes gets confused when the directory structure of subprojects changes, even after running `sbt clean` in all relevant directories. This still leaves some SBT files that break the compiler. A **dangerous** catch-all solution is to just remove all `.gitignore`-d files, which can be done with `git clean -xdf`. This does destroy all compilation directories, in addition to your custom files (e.g. `.eclipse`, `.idea`, etc.)

**Comment by niomaster** [comment] 2019-05-09 12:13
In addition, you can pass `-n` (`git clean -xdfn`) to show which files would be removed, and `-e` to not remove some files after all (e.g. `git clean -xdfe .idea`)

**Comment by bobismijnnaam** [comment] 2019-05-14 15:20
I also had this a few days ago after updating vercors with git pull and then doing `ant clean && ant`. Removing and cloning vercors from scratch fixed it for me.

**Comment by bobismijnnaam** [comment] 2021-05-03 09:49
Closing because of #603.

**Closed by bobismijnnaam** 2021-05-03 09:49 UTC
Labels: ​​​​​clarification needed
