### ISSUE TITLE
Post condition needs to be boolean depending on function body

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#213] opened 2019-05-14 15:18 UTC
I have the following code:

```
class Int {
  int val;
}

class MyClass {
  ensures \result.length > 0;
  ensures Perm(\result[0].val, 1);
  static seq<Int> lemma_concat_ok(seq<Int> xs, seq<Int> ys);

  ensures \result.length > 0;
  ensures Perm(\result[0].val, 1);
  static seq<Int> lemma_concat_bad(seq<Int> xs, seq<Int> ys) = xs + ys;
}
```

Output:
```
Parsed 1 file(s) in: 217ms
Comparing Integer with 0 as Integer
=== lemma-plus.pvl                 ===
   9 
  10   ensures \result.length > 0;
              [-----------------------
  11   ensures Perm(\result[0].val, 1);
               -----------------------]
  12   static seq<Int> lemma_concat_bad(seq<Int> xs, seq<Int> ys) = xs + ys;
  13 }
-----------------------------------------
  post condition of function lemma_concat_bad is not a boolean
=========================================
At file lemma-plus.pvl from line 10 column 3 until line 12 column 71: type error
Triggered by file lemma-plus.pvl from line 10 column 3 until line 12 column 71:
The final verdict is Error
entire run took 278 ms
```

Neither of the two functions make much sense, but I would expect vercors to either accept the postcondition in both cases or reject it in both cases, not something inbetween. Is this a bug or is this a subtle case in PVL semantics?

**Comment by niomaster** [comment] 2019-07-18 12:36
I believe that this is roughly intended behaviour. The first function does not have a body, which is intended for function for which we assume the contract. These are marked as plain, and so may reason about permissions. The second function uses syntax intended for pure functions, hence the `=`. Pure functions may not reason about permissions, so the type checker complains.

**Closed** 2019-07-18 12:37 UTC
Labels: question
