### ISSUE TITLE
Dividing by zero

### ISSUE THREAD

**Issue by sakehl** [utwente-fmt/vercors#1112] opened 2023-11-20 10:38 UTC
A division by zero error does not get reported correctly anymore.

This program:
```java
int main(){
    int x = 5/0;
}
```

Gives:
```
[INFO] Starting verification
[ERROR] Unrecoverable error: class vct.col.ast.IntegerValue cannot be cast to class vct.col.ast.DividingExpr (vct.col.ast.IntegerValue and vct.col.ast.DividingExpr are in unnamed module of loader 'app')
java.lang.ClassCastException: class vct.col.ast.IntegerValue cannot be cast to class vct.col.ast.DividingExpr (vct.col.ast.IntegerValue and vct.col.ast.DividingExpr are in unnamed module of loader 'app')
        at viper.api.backend.SilverBackend.defer(SilverBackend.scala:312)
        at viper.api.backend.SilverBackend.defer$(SilverBackend.scala:310)
        at viper.api.backend.silicon.Silicon.defer(Silicon.scala:42)
```

I think the Silver backend gives back the divisor (in this case IntegerValue(0)) instead of the whole division.

**Comment by pieter-bos** [comment] 2023-11-20 10:50
duplicate of #965 (thanks though)

**Closed by pieter-bos** 2023-11-20 10:50 UTC

**Comment by sakehl** [comment] 2023-11-20 10:53
Ah, woops missed that issue, but thanks!
