### ISSUE TITLE
Illegal argument count without position

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#125] opened 2018-09-26 09:52 UTC
When I write ``a+{b}`` instead of ``a+seq<int>{b}``, I get the error message ``illegal argument count``. The error is fine (the message might be improved), but it does not come with a file position and gives a Java stack trace.

Note: we still need a minimal example to reproduce this error. Can you find one for me?

Once this is fixed, please update https://github.com/utwente-fmt/vercors/wiki/What-does-this-VerCors-error-message-mean%3F

**Comment by niomaster** [comment] 2020-05-05 15:41
Currently if you do not specify a container type (e.g. with `seq<int>...`), `{ ... }` denotes a set. when I add a sequence to a set, for example by doing this:

```
class T {
    void test() {
        seq<int> a = seq<int>{1, 2};
        seq<int> b = a + {3};
    }
}
```

I receive the error "At file examples/private/125.pvl from line 4 column 21 until line 4 column 27: Types of left and right-hand side argument are uncomparable: Sequence<Integer>/Set<Integer>", which I think is fine.

I'm closing this for now because I can't reproduce the problem, but feel free to reopen if you have an example of when this happens!

**Closed by niomaster** 2020-05-05 15:41 UTC
Labels: ​bug, ​​frontend: all, ​​​​​clarification needed
