### ISSUE TITLE
NotWellFormed:InsufficientPermission for par block with 3 different threads

### ISSUE THREAD

**Issue by petravandenbos-utwente** [utwente-fmt/vercors#505] opened 2020-08-04 14:32 UTC
Code:
```
class Role {
	int x;
	int left;
	
	ensures Perm(x, write) ** Perm(left, write);
	ensures x == v;
	Role (int v) {
		x = v;
	}	
}

class Main {
	Role a;
	Role b;
	Role c;
	
	ensures Perm(a, 1\2) ** Perm(b,1\2) ** Perm(c,1\2);
	ensures a != null ** b!= null ** c != null;
	ensures Perm(a.x, write) ** Perm(b.x, write) ** Perm(c.x, write);
	ensures Perm(a.left, write) ** Perm(b.left, write) ** Perm(c.left, write);
	ensures a != b ** b != c ** a != c;
	Main() {
		a = new Role(0);
		b = new Role(8);
		c = new Role(4);
	}
	
	context Perm(a, 1\2) ** Perm(b,1\2) ** Perm(c,1\2);
	context a != null ** b!= null ** c != null;
	context Perm(a.x, 1) ** Perm(b.x, 1) ** Perm(c.x, 1);
	context Perm(a.left, 1) ** Perm(b.left, 1) ** Perm(c.left, 1);
	void something() {
		par (int tid=0..3)
		context Perm(a, 1\9) ** Perm(b,1\9) ** Perm(c,1\9);
		context a != null;
		context b!= null;
		context c != null;
		context tid == 0 ==> Perm(a.x, 1\2) ** Perm(b.left, 1);
		context tid == 1 ==> Perm(b.x, 1\2) ** Perm(c.left, 1);
		context tid != 0 && tid != 1 ==> Perm(c.x, 1\2) ** Perm(a.left, 1);
		{
			if(tid == 0) {
				b.left = a.x;
			} else if(tid == 1) {
				c.left = b.x;
			} else { //if(tid == 2) 
				a.left = c.x;
			}
		}
	}
}
```

Error messages:
```
[progress] [98%] check took 40 ms
[progress] Applying silver ...
[progress] verifying with builtin silicon backend
[progress] conversion took 80ms
[warning] [viper] No triggers available for quantifier at <no position>
[warning] [viper] No triggers available for quantifier at <no position>
[warning] [viper] No triggers available for quantifier at <no position>
Errors! (2)
=== parallelwhile3.pvl             ===
  35 	context Perm(a.left, 1) ** Perm(b.left, 1) ** Perm(c.left, 1);
  36 	void something() {
         [---------------
  37 		par (int tid=0..3)
  38 		context Perm(a, 1\9) ** Perm(b,1\9) ** Perm(c,1\9);
  39 		context a != null;
  40 		context b!= null;
  41 		context c != null;
  42 		context tid == 0 ==> Perm(a.x, 1\2) ** Perm(b.left, 1);
  43 		context tid == 1 ==> Perm(b.x, 1\2) ** Perm(c.left, 1);
  44 		context tid != 0 && tid != 1 ==> Perm(c.x, 1\2) ** Perm(a.left, 1);
  45 		{
  46 			if(tid == 0) {
  47 				b.left = a.x;
  48 			} else if(tid == 1) {
  49 				c.left = b.x;
  50 			} else { //if(tid == 2) 
  51 				a.left = c.x;
  52 			}
  53 		}
     --]
  54 		/*
  55 		loop_invariant Perm(a, 1\2) ** Perm(b,1\2) ** Perm(c,1\2);
-----------------------------------------
  NotWellFormed:InsufficientPermission
=========================================
=== parallelwhile3.pvl             ===
  37 		par (int tid=0..3)
  38 		context Perm(a, 1\9) ** Perm(b,1\9) ** Perm(c,1\9);
             [-
  39 		context a != null;
              -]
  40 		context b!= null;
  41 		context c != null;
-----------------------------------------
  caused by
=========================================
=== parallelwhile3.pvl             ===
  35 	context Perm(a.left, 1) ** Perm(b.left, 1) ** Perm(c.left, 1);
  36 	void something() {
     [-------------------
  37 		par (int tid=0..3)
  38 		context Perm(a, 1\9) ** Perm(b,1\9) ** Perm(c,1\9);
  39 		context a != null;
  40 		context b!= null;
  41 		context c != null;
  42 		context tid == 0 ==> Perm(a.x, 1\2) ** Perm(b.left, 1);
  43 		context tid == 1 ==> Perm(b.x, 1\2) ** Perm(c.left, 1);
  44 		context tid != 0 && tid != 1 ==> Perm(c.x, 1\2) ** Perm(a.left, 1);
  45 		{
  46 			if(tid == 0) {
  47 				b.left = a.x;
  48 			} else if(tid == 1) {
  49 				c.left = b.x;
  50 			} else { //if(tid == 2) 
  51 				a.left = c.x;
  52 			}
  53 		}
     --]
  54 		/*
  55 		loop_invariant Perm(a, 1\2) ** Perm(b,1\2) ** Perm(c,1\2);
-----------------------------------------
  CallPreCondition:InsufficientPermission
=========================================
=== parallelwhile3.pvl             ===
  36 	void something() {
  37 		par (int tid=0..3)
                  [-
  38 		context Perm(a, 1\9) ** Perm(b,1\9) ** Perm(c,1\9);
                   -]
  39 		context a != null;
  40 		context b!= null;
-----------------------------------------
  caused by
=========================================
[progress] task Viper verification took 4071 ms
[progress]  ... pass took 460 ms
The final verdict is Fail
[progress] entire run took 14294 ms
```

**Comment by niomaster** [comment] 2020-08-12 14:40
This is a simplification problem that is partially solved in the new viper branch. Solving this error now produces:

```
Errors! (1)
=== examples/private/505.pvl       ===
  28 	context Perm(a, 1\2) ** Perm(b,1\2) ** Perm(c,1\2);
  29 	context a != null ** b!= null ** c != null;
                                            [------------
  30 	context Perm(a.x, 1) ** Perm(b.x, 1) ** Perm(c.x, 1);
                                             ------------]
  31 	context Perm(a.left, 1) ** Perm(b.left, 1) ** Perm(c.left, 1);
  32 	void something() {
-----------------------------------------
  PostConditionFailed:InsufficientPermission
=========================================
=== examples/private/505.pvl       ===
  28 	context Perm(a, 1\2) ** Perm(b,1\2) ** Perm(c,1\2);
  29 	context a != null ** b!= null ** c != null;
                                                 [---
  30 	context Perm(a.x, 1) ** Perm(b.x, 1) ** Perm(c.x, 1);
                                                  ---]
  31 	context Perm(a.left, 1) ** Perm(b.left, 1) ** Perm(c.left, 1);
  32 	void something() {
-----------------------------------------
  caused by
=========================================
```

Arguably this is again a simplification failure, but this time I'm not so sure it's Vercors' fault. The cause is the expression:

```
context tid != 0 && tid != 1 ==> Perm(c.x, 1\2) ** Perm(a.left, 1);
```

This becomes in viper, in the kernel contract:

```
  ensures (forall tid: Int :: 0 <= tid && tid < 3 && (tid != 0 && tid != 1) ==> acc(diz.field_Main_c.field_Role_x, 1 / 2))
  ensures (forall tid: Int :: 0 <= tid && tid < 3 && (tid != 0 && tid != 1) ==> acc(diz.field_Main_a.field_Role_left, write))
```

There is no admissable trigger here (tid does not occur in the body of the quantifier) and there is no simplification general enough to catch this I think. Of course rewriting it to `context tid == 2 ==> Perm(c.x, 1\2) ** Perm(a.left, 1);` solves it, so I think we can leave this issue at this.

**Comment by bobismijnnaam** [comment] 2020-08-13 09:17
Are you sure @niomaster? The oh-no branch still gives me the old error with Petra's code. (Not doubting you, just wanted to tinker with Petra's code to see if I could get it to work with a dud identity function, but couldn't get it to work)

**Comment by niomaster** [comment] 2020-08-13 10:40
Sorry about the double work, I just committed some work I did on the branch.

**Comment by bobismijnnaam** [comment] 2020-08-28 09:41
I managed to work around this by introducing a dud identity function:

	ensures \result == x;
	pure static int myId(int x) = x;

	context Perm(a, 1\2) ** Perm(b,1\2) ** Perm(c,1\2);
	context a != null ** b!= null ** c != null;
	context Perm(a.x, 1) ** Perm(b.x, 1) ** Perm(c.x, 1);
	context Perm(a.left, 1) ** Perm(b.left, 1) ** Perm(c.left, 1);
	void something() {
		par (int tid=0..3)
		context Perm(a, 1\9) ** Perm(b,1\9) ** Perm(c,1\9);
		context a != null;
		context b!= null;
		context c != null;
		context tid == 0 ==> Perm(a.x, 1\2) ** Perm(b.left, 1);
		context tid == 1 ==> Perm(b.x, 1\2) ** Perm(c.left, 1);
		context myId(tid) != 0 && tid != 1 ==> Perm(c.x, 1\2) ** Perm(a.left, 1);
		{
			if(tid == 0) {
				b.left = a.x;
			} else if(tid == 1) {
				c.left = b.x;
			} else { //if(tid == 2)
				a.left = c.x;
			}
		}
	}

I've looked at the output and we don't generate a trigger for the last `context`. So I guess this allows viper to derive it's own trigger. With the two workarounds listed in this issue I think we can close it.

**Closed by bobismijnnaam** 2020-08-28 09:41 UTC
Labels: ​enhancement, ​​​rewrite: general
