### ISSUE TITLE
Make leader election Java 6 lock passing again

### ISSUE THREAD

**Issue by raulmonti** [utwente-fmt/vercors#514] opened 2020-08-19 09:53 UTC
The leader election example is a very nice example about Futures. It is one of the more involved and interesting that we have, and thus it will be convenient to have it fully passing again. Also look at the Java 6 lock example which is having troubles too. (I believe that both examples will be marked as Failing soon). 

Fixing these examples will also bring light into what is the problem we are currently facing wrt the new viper back end and our verifications randomly failing.

**Comment by bobismijnnaam** [comment] 2020-08-19 12:33
See also my comment [here](https://github.com/utwente-fmt/vercors/issues/509#issuecomment-673329108). In short: to give some guarantee that the problematic test cases keep functioning, we should keep typechecking/appling all internal passes to the problematic test cases (e.g. all tests in the suite `problem-fail`), but not check them with Viper (since that is obviously problematic for those test cases). I think this would be a good idea since it might take a very long time to fix the instability of the test cases, and I don't want code that is needed to verify them to break in the mean time.

For the unstable tests, we could in the meantime add an option to retry a test multiple times. However that might be a slippery slope, and a fully functioning test suite is far more preferable.

**Comment by bobismijnnaam** [comment] 2021-07-08 11:53
#651 explains the idea of doing tests partially. Leader elect was merged in #635, but it still fails sometimes (though hard to reproduce for me).

**Comment by bobismijnnaam** [comment] 2021-07-13 15:09
leader elect and OpenMPSectionReducedFail1 are marked as `--stop-before-backend` in #657. Possibly Java6Lock will be marked as `--stop-before-backend` there as well.

**Comment by pieter-bos** [comment] 2023-10-09 11:00
The unsupported concepts used in these examples are further discussed here:

* [Process Models](https://github.com/utwente-fmt/vercors/discussions/822)
* [Atomics](https://github.com/utwente-fmt/vercors/discussions/829)

**Closed by pieter-bos** 2023-10-09 11:00 UTC
Labels: A-Bug, M-ex
