### ISSUE TITLE
Insufficient permission when evenly dividing permission between par workers

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#215] opened 2019-05-15 12:28 UTC
I have the following program:
```
class MyClass {
  given frac p;
  requires p != none;
  invariant xs != null;
  requires (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], p));
  void foo(int[] xs) {
    int N = 3;
    par (int tid = 0..N)
      requires N > 0;
      context (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], p/N));
    { }
  }
}
```

I expect it to verify, since the permission should be divided evenly. But it doesn't.

Output:
```
running verify
No triggers available for quantifier at <no position>
No triggers available for quantifier at <no position>
finished verify
Errors! (1)
reporting CallPreCondition error
=== par-perm.pvl                   ===
   6   void foo(int[] xs) {
   7     int N = 3;
        [--------------------
   8     par (int tid = 0..N)
   9       requires N > 0;
  10       context (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], p/N));
  11     {
  12       // assert N > 0;
  13     }
     -----]
  14   }
  15 }
-----------------------------------------
  CallPreCondition:InsufficientPermission
=========================================
=== par-perm.pvl                   ===
   8     par (int tid = 0..N)
   9       requires N > 0;
                                                                 [-----
  10       context (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], p/N));
                                                                  -----]
  11     {
  12       // assert N > 0;
-----------------------------------------
  caused by
=========================================
The final verdict is Fail
entire run took 5865 ms
```

If you inline the N = 3 everywhere it also fails. Funnily enough, the sample works fine when N = 2 is hardcoded. After talking about it with Sebastiaan he thought it probably is (hopefully paraphrasing this correctly) a bug in the rule rewriter for permissions/asserts.

**Comment by niomaster** [comment] 2020-01-23 13:01
I think this is the old case of "a boolean expression is embedded in a \forall*" case, which should be fixed now. Someone should confirm with the current `dev`.

**Comment by niomaster** [comment] 2020-05-04 14:43
With new syntax:

```
class MyClass {
  given frac p;
  requires p != none;
  context_everywhere xs != null;
  requires (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], p));
  void foo(int[] xs) {
    int N = 3;
    par (int tid = 0..N)
      requires N > 0;
      context (\forall* int i; 0 <= i && i < xs.length; Perm(xs[i], p\N));
    { }
  }
}
```

Cannot reproduce

**Closed by niomaster** 2020-05-04 14:43 UTC
Labels: ​bug, ​​​rewrite: general, ​​​​​clarification needed
