### ISSUE TITLE
Unclear type error: inline resources on static methods

### ISSUE THREAD

**Issue by JLedelay** [utwente-fmt/vercors#906] opened 2022-12-21 11:19 UTC
The following input:
```java
class C {
  //@ inline resource p() = true;

  //@ requires p();
  static void m() {
  }
}
```
Generates the following output:
```
A rewrite caused the AST to no longer typecheck:
======================================
Inlined from:
--------------------------------------
 At Test.java:4:16:
--------------------------------------
    2    //@ inline resource p() = true;
    3
                     [---
    4    //@ requires p();
                      ---]
    5    static void m() {
    6    }
--------------------------------------
 In definition:
--------------------------------------
 At Test.java:1:1:
--------------------------------------
      [------------
    1  class C {
    2    //@ inline resource p() = true;
    3
       ... (1 lines omitted)
    5    static void m() {
    6    }
    7  }
       -]
    8
--------------------------------------
Expected the type of this expression to be `C`, but got CStatics.
======================================
```
The type error is a little unclear. The definition points to the entire class, and it wasn't immediately clear to me that the reason this doesn't work is that inline resources are bound to instances of the class. In hindsight, it makes sense, but the error didn't help make this clear.

**Comment by niomaster** [comment] 2022-12-21 11:46
This is rooted in the fact that the resolver is bad at resolving static declarations, and resolving declarations in a static context: `p` should not have been resolved at all (though a warning would be nice).

By the way, "A rewrite caused the AST to no longer typecheck" indicates a `SystemError`, which is always just a straight up bug. We should make it more clear that that is the case: the error message may be useful to the user, but it is not all that important: the problem is the bug.

**Closed** 2023-10-09 13:55 UTC
Labels: A-Bug, F-Java
