### ISSUE TITLE
Futures using option types

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#64] opened 2017-04-05 13:00 UTC
For some reason option types cannot be used in combination with Futures (and possibly also Histories). Running VerCors (`vct --check-history --silver=silicon [filename]`) with the following code sample results in a failure (saying: The final verdict is Fail). However, no exception, track trace, or error description is given. 

```java
class Future {
  option<int> owner;

  modifies owner;
  requires owner == None;
  ensures owner == Some(threadid);
  process test(int threadid);
}
```

**Comment by niomaster** [comment] 2019-10-28 13:24
I can't reproduce this anymore (the example passes), so I'm closing the issue :)

**Closed by niomaster** 2019-10-28 13:24 UTC
Labels: bug
