### ISSUE TITLE
elect.pvl does not verify: Head operator

### ISSUE THREAD

**Issue by petravandenbos** [utwente-fmt/vercors#391] opened 2020-02-14 13:33 UTC
elect.pvl does not verify. I get the following debug information:

[debug] At Main.java:675: 
[debug] hre.lang.HREError: cannot map operator Head
[debug] At Main.java:675: 
[debug] 	at vct.silver.SilverExpressionMap.map(SilverExpressionMap.java:169)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.$anonfun$accept_simple$2(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard$(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.handle_standard(OperatorExpression.scala:10)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.accept_simple(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.generic.ASTNode.apply(ASTNode.java:189)
[debug] At Main.java:675: 
[debug] 	at vct.silver.SilverExpressionMap.map(SilverExpressionMap.java:90)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.$anonfun$accept_simple$2(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard$(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.handle_standard(OperatorExpression.scala:10)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.accept_simple(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.generic.ASTNode.apply(ASTNode.java:189)
[debug] At Main.java:675: 
[debug] 	at vct.silver.SilverExpressionMap.map(SilverExpressionMap.java:494)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.constant.StructValue.$anonfun$accept_simple$2(StructValue.scala:32)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard$(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.constant.StructValue.handle_standard(StructValue.scala:12)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.constant.StructValue.accept_simple(StructValue.scala:32)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.generic.ASTNode.apply(ASTNode.java:189)
[debug] At Main.java:675: 
[debug] 	at vct.silver.SilverExpressionMap.map(SilverExpressionMap.java:90)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.$anonfun$accept_simple$2(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard$(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.handle_standard(OperatorExpression.scala:10)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.accept_simple(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.generic.ASTNode.apply(ASTNode.java:189)
[debug] At Main.java:675: 
[debug] 	at vct.silver.SilverExpressionMap.map(SilverExpressionMap.java:86)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.$anonfun$accept_simple$2(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.util.VisitorHelper.handle_standard$(VisitorHelper.scala:22)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.handle_standard(OperatorExpression.scala:10)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.expr.OperatorExpression.accept_simple(OperatorExpression.scala:60)
[debug] At Main.java:675: 
[debug] 	at vct.col.ast.generic.ASTNode.apply(ASTNode.java:189)
[debug] At Main.java:675: 
[debug] 	at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:266)
[debug] At Main.java:675: 
[debug] 	at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:37)
[debug] At Main.java:675: 
[debug] 	at vct.silver.SilverBackend.TestSilicon(SilverBackend.java:81)
[debug] At Main.java:675: 
[debug] 	at vct.silver.SilverBackend.TestSilicon(SilverBackend.java:67)
[debug] At Main.java:675: 
[debug] 	at vct.main.Main$8.apply_pass(Main.java:740)
[debug] At Main.java:675: 
[debug] 	at vct.main.Main.main(Main.java:641)
[debug] At Main.java:676:
An unexpected error occured in VerCors! Please report an issue at https://github.com/utwente-fmt/vercors/issues/new. You can see the full exception by adding '--debug vct.main.Main' to the flags.
[debug] At Main.java:679:
The final verdict is Error

**Comment by petravandenbos** [comment] 2020-02-14 13:41
Before getting this error, I changed all /, occuring in fractions, into \

**Comment by niomaster** [comment] 2020-02-14 13:42
I moved it to the `problem-fail` suite here https://github.com/utwente-fmt/vercors/commit/30634fc143da62681b627de6c806a2be6e9a6948 so we would expect it to fail, but I don't quite remember why it stopped working.

**Comment by niomaster** [comment] 2020-02-14 13:45
This seems to just be an unmapped operator though, should be an easy fix around here https://github.com/utwente-fmt/vercors/blob/c232b3853004464f9d089d50e24c7ddb2b329d65/src/main/java/vct/silver/SilverExpressionMap.java#L109-L112

**Comment by petravandenbos-utwente** [comment] 2020-02-14 14:18
> Before getting this error, I changed all /, occuring in fractions, into \

These changes have now been pushed

**Comment by niomaster** [comment] 2020-02-21 14:45
Re-opening because the issue is `elect.pvl` not verifying, which is not solved after mapping the head operator.

I've traced the non-termination to a potential missing loop invariant. This is the requirement that cannot be proven:

https://github.com/utwente-fmt/vercors/blob/ebbe5b0e38054545489733efde7c75edfc079875/examples/known-problems/elect.pvl#L191

`mpi_send` is invoked in `elect` with parameter `msg` => `v` here:

https://github.com/utwente-fmt/vercors/blob/ebbe5b0e38054545489733efde7c75edfc079875/examples/known-problems/elect.pvl#L289

`v` is (I think) not mentioned in the loop invariants (unless [the `Future` line](https://github.com/utwente-fmt/vercors/blob/ebbe5b0e38054545489733efde7c75edfc079875/examples/known-problems/elect.pvl#L283) claims something about `v`), but the proof is now easily fixed by adding a loop invariant:

```
loop_invariant 0 <= v && v < maxvalue;
```

This results in VerCors terminating, and reporting a problem elsewhere in the example, so we're not quite done yet...

**Closed** 2020-03-04 08:46 UTC
Labels: ​bug, ​​​​backend: silicon
